<a href="https://colab.research.google.com/github/jmohsbeck1/jpmc_mle/blob/main/JPMC_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import libraries
import sys
import subprocess
import pandas as pd
import numpy as np
import scipy
import matplotlib
import sklearn

# load a sample dataset
url = 'https://goo.gl/bDdBiA'
data = pd.read_csv(url)
print(data.shape)

# load requirements.txt
#pip freeze > requirements.txt

(767, 9)

In [ ]:
# load a dataset from openML
import ssl 
ssl._create_default_https_context = ssl._create_unverified_context
import certifi
from sklearn.datasets import fetch_openml 
# Download the dataset from openml
dataset = fetch_openml(data_id=42803, as_frame=True)
#Extract feature matrix X and show 5 random samples
df = dataset["frame"]
pd.set_option("display.max_columns", None)
df.sample(5)

,Accident_Index,Vehicle_Reference_df_res,Vehicle_Type,Towing_and_Articulation,Vehicle_Manoeuvre,Vehicle_Location-Restricted_Lane,Junction_Location,Skidding_and_Overturning,Hit_Object_in_Carriageway,Vehicle_Leaving_Carriageway,Hit_Object_off_Carriageway,1st_Point_of_Impact,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_Home_Area_Type,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,Time,Local_Authority_(District),Local_Authority_(Highway),1st_Road_Class,1st_Road_Number,Road_Type,Speed_limit,Junction_Detail,Junction_Control,2nd_Road_Class,2nd_Road_Number,Pedestrian_Crossing-Human_Control,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Vehicle_Reference_df,Casualty_Reference,Casualty_Class,Sex_of_Casualty,Age_of_Casualty,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,Casualty_Type,Casualty_Home_Area_Type,Casualty_IMD_Decile
66916,201504WA15373,2,9.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,6.0,2.0,68.0,10.0,1598.0,1.0,1.0,1.0,331460.0,433880.0,-3.042025,53.796692,4.0,3.0,2.0,1.0,14/09/2015,2.0,15:30,71.0,E06000009,6.0,0.0,6.0,30.0,0.0,NaN,NaN,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,E01012745,2,1,1,2.0,68.0,10.0,3,0.0,0.0,0.0,0.0,0.0,9,1.0,2.0
193135,2015320122310,1,9.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,6.0,2.0,23.0,5.0,1360.0,1.0,12.0,1.0,496483.0,370335.0,-0.556381,53.221315,32.0,3.0,2.0,3.0,15/11/2015,1.0,13:08,352.0,E10000019,4.0,1003.0,3.0,40.0,0.0,NaN,NaN,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,E01026133,1,1,1,2.0,23.0,5.0,3,0.0,0.0,0.0,0.0,0.0,9,1.0,2.0
96628,2015100452315,2,19.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,2.0,1.0,61.0,9.0,1399.0,2.0,5.0,1.0,426025.0,563161.0,-1.595081,54.962406,10.0,3.0,3.0,2.0,09/07/2015,5.0,19:26,146.0,E08000020,3.0,184.0,3.0,50.0,0.0,NaN,NaN,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,E01008166,3,2,1,1.0,34.0,6.0,3,0.0,0.0,0.0,0.0,0.0,9,NaN,NaN
196208,2015331501052,2,9.0,0.0,18.0,0.0,8.0,5.0,0.0,0.0,0.0,2.0,1.0,6.0,2.0,19.0,4.0,1242.0,1.0,3.0,1.0,449004.0,304329.0,-1.277351,52.634507,33.0,3.0,2.0,2.0,19/07/2015,1.0,15:00,361.0,E10000018,5.0,3104.0,6.0,40.0,3.0,4.0,5.0,4103.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,2.0,1.0,E01025876,2,2,2,1.0,16.0,4.0,3,0.0,0.0,2.0,0.0,0.0,9,1.0,10.0
180357,2015300016562,2,9.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,1.0,45.0,7.0,2143.0,2.0,NaN,1.0,420470.0,331650.0,-1.697262,52.881927,30.0,3.0,4.0,2.0,04/11/2015,4.0,07:28,328.0,E10000007,3.0,50.0,3.0,70.0,0.0,NaN,NaN,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,2.0,1.0,E01019866,1,2,2,2.0,18.0,4.0,3,0.0,0.0,1.0,0.0,0.0,9,2.0,4.0

In [ ]:
# get number of rows, columns
df.shape

(363243, 67)

In [ ]:
# list columns
df.columns.values.tolist()

['Accident_Index',
 'Vehicle_Reference_df_res',
 'Vehicle_Type',
 'Towing_and_Articulation',
 'Vehicle_Manoeuvre',
 'Vehicle_Location-Restricted_Lane',
 'Junction_Location',
 'Skidding_and_Overturning',
 'Hit_Object_in_Carriageway',
 'Vehicle_Leaving_Carriageway',
 'Hit_Object_off_Carriageway',
 '1st_Point_of_Impact',
 'Was_Vehicle_Left_Hand_Drive?',
 'Journey_Purpose_of_Driver',
 'Sex_of_Driver',
 'Age_of_Driver',
 'Age_Band_of_Driver',
 'Engine_Capacity_(CC)',
 'Propulsion_Code',
 'Age_of_Vehicle',
 'Driver_Home_Area_Type',
 'Location_Easting_OSGR',
 'Location_Northing_OSGR',
 'Longitude',
 'Latitude',
 'Police_Force',
 'Accident_Severity',
 'Number_of_Vehicles',
 'Number_of_Casualties',
 'Date',
 'Day_of_Week',
 'Time',
 'Local_Authority_(District)',
 'Local_Authority_(Highway)',
 '1st_Road_Class',
 '1st_Road_Number',
 'Road_Type',
 'Speed_limit',
 'Junction_Detail',
 'Junction_Control',
 '2nd_Road_Class',
 '2nd_Road_Number',
 'Pedestrian_Crossing-Human_Control',
 'Pedestrian_Crossing-Physical_Facilities',
 'Light_Conditions',
 'Weather_Conditions',
 'Road_Surface_Conditions',
 'Special_Conditions_at_Site',
 'Carriageway_Hazards',
 'Urban_or_Rural_Area',
 'Did_Police_Officer_Attend_Scene_of_Accident',
 'LSOA_of_Accident_Location',
 'Vehicle_Reference_df',
 'Casualty_Reference',
 'Casualty_Class',
 'Sex_of_Casualty',
 'Age_of_Casualty',
 'Age_Band_of_Casualty',
 'Casualty_Severity',
 'Pedestrian_Location',
 'Pedestrian_Movement',
 'Car_Passenger',
 'Bus_or_Coach_Passenger',
 'Pedestrian_Road_Maintenance_Worker',
 'Casualty_Type',
 'Casualty_Home_Area_Type',
 'Casualty_IMD_Decile']

In [ ]:
# show number of unique values for each column
n = df.nunique(axis=0)
print("Number of unique values in each column :\n", n)

Number of unique values in each column :
 Accident_Index                        140056
Vehicle_Reference_df_res                  37
Vehicle_Type                              20
Towing_and_Articulation                    6
Vehicle_Manoeuvre                         18
                                       ...
Bus_or_Coach_Passenger                     5
Pedestrian_Road_Maintenance_Worker         3
Casualty_Type                             21
Casualty_Home_Area_Type                    3
Casualty_IMD_Decile                       10
Length: 67, dtype: int64

In [ ]:
# check for NaNs
df.isna()

,Accident_Index,Vehicle_Reference_df_res,Vehicle_Type,Towing_and_Articulation,Vehicle_Manoeuvre,Vehicle_Location-Restricted_Lane,Junction_Location,Skidding_and_Overturning,Hit_Object_in_Carriageway,Vehicle_Leaving_Carriageway,...,Age_Band_of_Casualty,Casualty_Severity,Pedestrian_Location,Pedestrian_Movement,Car_Passenger,Bus_or_Coach_Passenger,Pedestrian_Road_Maintenance_Worker,Casualty_Type,Casualty_Home_Area_Type,Casualty_IMD_Decile
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363238,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
363239,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
363240,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
363241,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
363242,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
# check for count of NaNs
df.isna().sum()

Accident_Index                            0
Vehicle_Reference_df_res                  0
Vehicle_Type                             62
Towing_and_Articulation                 379
Vehicle_Manoeuvre                       184
                                      ...
Bus_or_Coach_Passenger                   46
Pedestrian_Road_Maintenance_Worker      166
Casualty_Type                             0
Casualty_Home_Area_Type               39795
Casualty_IMD_Decile                   69577
Length: 67, dtype: int64

In [ ]:
# list column data types
df.dtypes

Accident_Index                         object
Vehicle_Reference_df_res                int64
Vehicle_Type                          float64
Towing_and_Articulation               float64
Vehicle_Manoeuvre                     float64
                                       ...
Bus_or_Coach_Passenger                float64
Pedestrian_Road_Maintenance_Worker    float64
Casualty_Type                           int64
Casualty_Home_Area_Type                object
Casualty_IMD_Decile                    object
Length: 67, dtype: object

In [ ]:
# extract numeric columns into numDF 
numbers=['int','int64', 'float64']
numDF = df.select_dtypes(include=numbers)
numDF.columns.values.tolist()

['Vehicle_Reference_df_res',
 'Vehicle_Type',
 'Towing_and_Articulation',
 'Vehicle_Manoeuvre',
 'Vehicle_Location-Restricted_Lane',
 'Junction_Location',
 'Skidding_and_Overturning',
 'Hit_Object_in_Carriageway',
 'Vehicle_Leaving_Carriageway',
 'Hit_Object_off_Carriageway',
 '1st_Point_of_Impact',
 'Was_Vehicle_Left_Hand_Drive?',
 'Journey_Purpose_of_Driver',
 'Engine_Capacity_(CC)',
 'Propulsion_Code',
 'Age_of_Vehicle',
 'Location_Easting_OSGR',
 'Location_Northing_OSGR',
 'Longitude',
 'Latitude',
 'Police_Force',
 'Accident_Severity',
 'Number_of_Vehicles',
 'Number_of_Casualties',
 'Day_of_Week',
 'Local_Authority_(District)',
 '1st_Road_Class',
 '1st_Road_Number',
 'Road_Type',
 'Speed_limit',
 'Junction_Detail',
 'Junction_Control',
 '2nd_Road_Class',
 '2nd_Road_Number',
 'Pedestrian_Crossing-Human_Control',
 'Pedestrian_Crossing-Physical_Facilities',
 'Light_Conditions',
 'Weather_Conditions',
 'Road_Surface_Conditions',
 'Special_Conditions_at_Site',
 'Carriageway_Hazards',
 'Urban_or_Rural_Area',
 'Did_Police_Officer_Attend_Scene_of_Accident',
 'Vehicle_Reference_df',
 'Casualty_Reference',
 'Casualty_Class',
 'Sex_of_Casualty',
 'Age_of_Casualty',
 'Age_Band_of_Casualty',
 'Casualty_Severity',
 'Pedestrian_Location',
 'Pedestrian_Movement',
 'Car_Passenger',
 'Bus_or_Coach_Passenger',
 'Pedestrian_Road_Maintenance_Worker',
 'Casualty_Type']

In [ ]:
# Extract categorical columns inot catDF
catDF = df.select_dtypes(exclude=numbers)
catDF.columns.values.tolist()

['Accident_Index',
 'Sex_of_Driver',
 'Age_of_Driver',
 'Age_Band_of_Driver',
 'Driver_Home_Area_Type',
 'Date',
 'Time',
 'Local_Authority_(Highway)',
 'LSOA_of_Accident_Location',
 'Casualty_Home_Area_Type',
 'Casualty_IMD_Decile']

In [ ]:
# check for duplicates
dupes = df[df.duplicated()]
dupes.columns.values.tolist()

['Accident_Index',
 'Vehicle_Reference_df_res',
 'Vehicle_Type',
 'Towing_and_Articulation',
 'Vehicle_Manoeuvre',
 'Vehicle_Location-Restricted_Lane',
 'Junction_Location',
 'Skidding_and_Overturning',
 'Hit_Object_in_Carriageway',
 'Vehicle_Leaving_Carriageway',
 'Hit_Object_off_Carriageway',
 '1st_Point_of_Impact',
 'Was_Vehicle_Left_Hand_Drive?',
 'Journey_Purpose_of_Driver',
 'Sex_of_Driver',
 'Age_of_Driver',
 'Age_Band_of_Driver',
 'Engine_Capacity_(CC)',
 'Propulsion_Code',
 'Age_of_Vehicle',
 'Driver_Home_Area_Type',
 'Location_Easting_OSGR',
 'Location_Northing_OSGR',
 'Longitude',
 'Latitude',
 'Police_Force',
 'Accident_Severity',
 'Number_of_Vehicles',
 'Number_of_Casualties',
 'Date',
 'Day_of_Week',
 'Time',
 'Local_Authority_(District)',
 'Local_Authority_(Highway)',
 '1st_Road_Class',
 '1st_Road_Number',
 'Road_Type',
 'Speed_limit',
 'Junction_Detail',
 'Junction_Control',
 '2nd_Road_Class',
 '2nd_Road_Number',
 'Pedestrian_Crossing-Human_Control',
 'Pedestrian_Crossing-Physical_Facilities',
 'Light_Conditions',
 'Weather_Conditions',
 'Road_Surface_Conditions',
 'Special_Conditions_at_Site',
 'Carriageway_Hazards',
 'Urban_or_Rural_Area',
 'Did_Police_Officer_Attend_Scene_of_Accident',
 'LSOA_of_Accident_Location',
 'Vehicle_Reference_df',
 'Casualty_Reference',
 'Casualty_Class',
 'Sex_of_Casualty',
 'Age_of_Casualty',
 'Age_Band_of_Casualty',
 'Casualty_Severity',
 'Pedestrian_Location',
 'Pedestrian_Movement',
 'Car_Passenger',
 'Bus_or_Coach_Passenger',
 'Pedestrian_Road_Maintenance_Worker',
 'Casualty_Type',
 'Casualty_Home_Area_Type',
 'Casualty_IMD_Decile']

In [ ]:
# count duplicates for each column
dups = df.pivot_table(index = ['Accident_Index'], aggfunc = 'size')
print(dups)

Accident_Index
201501BS70001     1
201501BS70002     1
201501BS70004     1
201501BS70005     1
201501BS70008     2
                 ..
2015984139115     3
2015984139715     2
2015984140215     4
2015984140515     9
2015984141415    91
Length: 140056, dtype: int64

In [ ]:
# count number of unique values for each column
df.nunique()

Accident_Index                        140056
Vehicle_Reference_df_res                  37
Vehicle_Type                              20
Towing_and_Articulation                    6
Vehicle_Manoeuvre                         18
                                       ...
Bus_or_Coach_Passenger                     5
Pedestrian_Road_Maintenance_Worker         3
Casualty_Type                             21
Casualty_Home_Area_Type                    3
Casualty_IMD_Decile                       10
Length: 67, dtype: int64